# Generated by Django 3.0.2 on 2020-03-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=16, null=True, unique=True)),
                ('passWord', models.CharField(max_length=16, null=True)),
                ('gender', models.IntegerField(choices=[(0, '先生'), (1, '女士')], default=0)),
            ],
        ),
    ]
