# Generated by Django 3.0.2 on 2020-03-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlist',
            table='userList',
        ),
    ]
