# Generated by Django 3.0.2 on 2020-03-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0002_auto_20200331_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetdetail',
            name='sheetName',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
