# Generated by Django 3.0.2 on 2020-03-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0003_sheetdetail_sheetname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taglist',
            name='sheetId',
        ),
        migrations.AddField(
            model_name='taglist',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
