# Generated by Django 3.0.2 on 2020-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0004_auto_20200331_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taglist',
            name='category',
            field=models.CharField(max_length=16),
        ),
    ]
