# Generated by Django 3.0.2 on 2020-04-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0007_auto_20200401_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsheet',
            name='sheetName',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
