# Generated by Django 3.0.2 on 2020-04-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0009_musicsheet_ismusicapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiclist',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='mvId',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='name',
        ),
        migrations.AlterField(
            model_name='musiclist',
            name='musicId',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
