# Generated by Django 3.0.2 on 2020-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0010_auto_20200406_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='musiclist',
            name='musicId',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
