# Generated by Django 3.0.2 on 2020-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0013_auto_20200407_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsheet',
            name='sheetId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sheetdetail',
            name='sheetId',
            field=models.BigIntegerField(unique=True),
        ),
    ]
